# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ignore_word', models.TextField()),
                ('mandatory_word', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group_found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
                ('key_for_found', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_log', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=110, unique=True)),
                ('prioritet', models.CharField(default=50, max_length=10)),
                ('time_last_check', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('wait', 'Wait'), ('active', 'Active'), ('stop', 'Stop')], default='Wait', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vkcity',
            fields=[
                ('city_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vkpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField()),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('date_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Vkuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(default='')),
                ('last_name', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Vkcity')),
            ],
        ),
        migrations.AddField(
            model_name='vkpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Vkuser'),
        ),
        migrations.AddField(
            model_name='vkpost',
            name='user_ignore_post',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group_found',
            name='url',
            field=models.ManyToManyField(blank=True, to='spider.Url'),
        ),
        migrations.AddField(
            model_name='filter',
            name='author_ignore',
            field=models.ManyToManyField(blank=True, to='spider.Vkuser'),
        ),
        migrations.AddField(
            model_name='filter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
