# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20170620_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_url',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(),
        ),
    ]
