# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author_url',
            field=models.URLField(),
        ),
    ]
