# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0008_auto_20170624_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
