# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0010_auto_20170624_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('author', models.TextField(max_length=50)),
                ('author_url', models.URLField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('date_url', models.URLField()),
                ('status', models.TextField(max_length=20, null=True)),
            ],
        ),
    ]
